CREATE TABLE PROFESORADO(
	NOMBRE		VARCHAR2(40) UNIQUE,
	APELLIDO1	VARCHAR2(40),
	APELLIDO2	VARCHAR2(40),
	NIF_PROF	CHAR(9),
	DIRECCION	VARCHAR2(60),
	TITULACION	VARCHAR2(60),
	SALARIO		NUMBER(7,2) NOT NULL
	);
	
ALTER TABLE PROFESORADO ADD CONSTRAINT PK_PROFESORADO
PRIMARY KEY(NIF_PROF);
	
CREATE TABLE CURSOS(
	NOMBRE			VARCHAR2(40) UNIQUE,
	COD_CURSO		NUMBER(4),
	NIF_PROF		CHAR(9),
	MAX_ALUMNOS		NUMBER(3),
	FECHA_INICIO	DATE,
	FECHA_FIN		DATE,
	HORAS_TOTALES	NUMBER(5) NOT NULL
	);

ALTER TABLE CURSOS ADD CONSTRAINT PK_CURSOS
PRIMARY KEY(COD_CURSO);

ALTER TABLE CURSOS ADD CONSTRAINT FK_CURSOS
FOREIGN KEY(NIF_PROF)
REFERENCES PROFESORADO(NIF_PROF)
ON DELETE CASCADE;

ALTER TABLE CURSOS ADD CONSTRAINT CK_FECHAS
CHECK (FECHA_INICIO < FECHA_FIN);

CREATE TABLE ALUMNADO(
	NOMBRE				VARCHAR2(40),
	APELLIDO1			VARCHAR2(40),
	APELLIDO2			VARCHAR2(40),
	NIF_ALUMNO			CHAR(9),
	DIRECCION			VARCHAR2(60),
	SEXO				CHAR(1),
	FECHA_NACIMIENTO	DATE,
	COD_CURSO			NUMBER(4)
	);
	
ALTER TABLE ALUMNADO ADD CONSTRAINT PK_ALUMNADO
PRIMARY KEY(NIF_ALUMNO);

ALTER TABLE ALUMNADO ADD CONSTRAINT FK_ALUMNADO
FOREIGN KEY(COD_CURSO)
REFERENCES CURSO(COD_CURSO)
ON DELETE CASCADE;

ALTER TABLE ALUMNADO ADD CONSTRAINT CK_SEXO_ALUMNADO
CHECK (SEXO IN ('H', 'M'));

ALTER TABLE ALUMNADO ADD EDAD NUMBER(3);

ALTER TABLE ALUMNADO ADD CONSTRAINT CK_EDAD_ALUMNADO
CHECK (EDAD BETWEEN 14 AND 65);

ALTER TABLE CURSOS ADD CONSTRAINT CK_HORAS_TOTALES
CHECK (HORAS_TOTALES IN ('30', '40', '60'));

ALTER TABLE CURSOS ADD CONSTRAINT CK_MAX_ALUMNOS
CHECK (MAX_ALUMNOS >=15);

ALTER TABLE ALUMNOS DROP CONSTRAINT CK_SEXO_ALUMNADO;

ALTER TABLE PROFESORADO DROP COLUMN DIRECCION;

ALTER TABLE PROFESORADO DROP CONSTRAINT PK_PROFESORADO CASCADE;

ALTER TABLE PROFESORADO ADD CONSTRAINT PK_PROFESORADO
PRIMARY KEY(NOMBRE, APELLIDO1, APELLIDO2);


RENAME PROFESORADO TO TUTORIAS;

DROP TABLE ALUMNADO;

CREATE USER C##FORTES IDENTIFIED BY BD02;

GRANT ALL ON CURSOS TO C##FORTES;

REVOKE ALTER, UPDATE ON CURSOS FROM C##FORTES;



