CREATE TABLE alumno(
    NUMMATRICULA    NUMBER(3) PRIMARY KEY ,
    NOMBRE          VARCHAR2(80) ,
    FECHANACIMIENTO DATE ,
    TELEFONO        CHAR(9) );
    
CREATE TABLE profesor(
    IDPROFESOR      NUMBER(2) PRIMARY KEY,
    NIF_P           CHAR(9) UNIQUE,
    NOMBBRE         VARCHAR2(50),
    ESPECIALIDAD    VARCHAR2(50),
    TELEFONO        CHAR(9));
   
CREATE TABLE asignatura(
    CODASIGNATURA CHAR(6) PRIMARY KEY,
    NOMBRE        VARCHAR2(30),
    IDPROFESOR    NUMBER(3) REFERENCES profesor (IDPROFESOR));
    
CREATE TABLE recibe(
    NUMMATRICULA    NUMBER(3),
    CODASIGNATURA   CHAR(6),
    CURSOESCOLAR    CHAR(9)
    PRIMARY KEY (NUMMATRICULA, CODASIGNATURA, CURSOESCOLAR)
    FOREIGN KEY (NUMMATRICULA)  REFERENCES alumno (NUMMATRICULA)
    FOREIGN KEY (CODASIGNATURA) REFERENCES asignatura (CODASIGNATURA));
    
