CREATE TABLE MUNICIPIO(
	ID			CHAR(4) CONSTRAINT PK_MUNICIPIO PRIMARY KEY,
	NOMBRE		VARCHAR2(40) CONSTRAINT NN_NOMBRE NOT NULL,
	COD_POSTAL	CHAR(5),
	PROVINCIA	VARCHAR2(40)
	);
	
CREATE TABLE VIVIENDA(
	ID			 CHAR(4) CONSTRAINT PK_VIVIENDA PRIMARY KEY,
	TIPO_VIA	 VARCHAR2(10) DEFAULT 'CALLE',
	NOMBRE_VIA	 VARCHAR2(50) CONSTRAINT NN_NOMBRE_VIA NOT NULL,
	NUMERO		 NUMBER(3) CONSTRAINT NN_NUMERO NOT NULL,
	ID_MUNICIPIO CHAR(4) CONSTRAINT FK_ID REFERENCES MUNICIPIO (ID)
	);
	
CREATE TABLE PERSONA(
	DNI			CHAR(9) CONSTRAINT PK_PERSONA PRIMARY KEY,
	NOMBRE		VARCHAR2(40) CONSTRAINT NN_NOMBRE_PERSONA NOT NULL,
	FECHA_NAC	DATE,
	SEXO		CHAR(1),
	ID_VIVIENDA	CHAR(4) CONSTRAINT FK_VIVIENDA REFERENCES VIVIENDA (ID),
	CONSTRAINT CK_SEXO CHECK (SEXO IN ('H', 'M'))
	);
	
CREATE TABLE POSEE(
	DNI			CHAR(9) CONSTRAINT FK_PERSONA FOREIGN KEY REFERENCES PERSONA (DNI),
	ID_VIVIENDA	CHAR(4) CONSTRAINT FK_VIVIENDA FOREIGN KEY REFERENCES VIVIENDA(ID), 
	CONSTRAINT PK_POSEE PRIMARY KEY (DNI, ID_VIVIENDA)
	
	);
	
CREATE TABLE CABEZA_FAMILIA(
	DNI			CHAR(9) CONSTRAINT PK_CABEZA_FAMILIA PRIMARY KEY,
	ID_VIVIENDA	CHAR(4) CONSTRAINT UK_ID_VIVIENDA UNIQUE,
	CONSTRAINT FK1_PER FOREIGN KEY (DNI)
		REFERENCES PERSONA(DNI),
	CONSTRAINT FK2_VIV (ID_VIVIENDA)
		REFERENCES VIVIENDA(ID)
	);