CREATE TABLE PARQUE_NATURAL(
	CODPN				NUMBER(4),
	NOMBRE				VARCHAR2(40),
	FECHA_DECLARACION	DATE
	);
	
ALTER TABLE PARQUE_NATURAL ADD CONSTRAINT PK_PARQUE_NATURAL
	PRIMARY KEY(CODPN);
	
CREATE TABLE COMUNIDAD_AUTONOMA(
	CODCA			NUMBER(4),
	NOMBRE			VARCHAR2(40),
	ORG_RESPONSABLE	VARCHAR2(40)
	);
	
ALTER TABLE COMUNIDAD_AUTONOMA ADD CONSTRAINT PK_COMUNIDAD_AUTONOMA
	PRIMARY KEY(CODCA);
	
CREATE TABLE CA_PN(
	CODCA		NUMBER(4),
	CODPN		NUMBER(3),	
	SUPERFICIE	NUMBER(7,2)
	);
	
ALTER TABLE CA_PN ADD CONSTRAINT PK_CA_PN
	PRIMARY KEY(CODCA, CODPN);
	
ALTER TABLE CA_PN ADD CONSTRAINT FK1_CA_PN
	FOREIGN KEY(CODCA)
	REFERENCES COMUNIDAD_AUTONOMA(CODCA);
	
ALTER TABLE CA_PN ADD CONSTRAINT FK2_CA_PN
	FOREIGN KEY(CODPN)
	REFERENCES PARQUE_NATURAL(CODPN);
	
CREATE TABLE ENTRADA(
	COD_ENTRADA	NUMBER(2),
	CODPN		NUMBER(4)
	);
	
ALTER TABLE ENTRADA ADD CONSTRAINT PK_ENTRADA
	PRIMARY KEY(COD_ENTRADA)
	
ALTER TABLE ENTRADA ADD CONSTRAINT FK_ENTRADA
	FOREIGN KEY(CODPN)
	REFERENCES PARQUE_NATURAL(CODPN);
	
CREATE TABLE ALOJAMIENTO(
	COD_ALOJAMIENTO	NUMBER(2),
	CATEGORIA		VARCHAR2(20),
	CAPACIDAD		NUMBER(3),
	CODPN			NUMBER(4)
	);
	
ALTER TABLE ALOJAMIENTO ADD CONSTRAINT PK_ALOJAMIENTO
	PRIMARY KEY(COD_ALOJAMIENTO);
	
ALTER TABLE ALOJAMIENTO ADD CONSTRAINT FK_ALOJAMIENTO
	FOREIGN KEY(CODPN)
	REFERENCES PARQUE_NATURAL(CODPN);
	
CREATE TABLE EXCURSION(
	COD_EXCURSION	NUMBER(4),
	FECHA			DATE,
	HORA			NUMBER(10),
	APIE			CHAR(1),
	COD_ALOJAMIENTO	NUMBER(4)
	);
	
ALTER TABLE EXCURSION ADD CONSTRAINT PK_EXCURSION
	PRIMARY KEY(COD_EXCURSION);
	
ALTER TABLE EXCURSION ADD CONSTRAINT FK_EXCURSION
	FOREIGN KEY(COD_ALOJAMIENTO)
	REFERENCES ALOJAMIENTO(COD_ALOJAMIENTO);
	
ALTER TABLE EXCURSION ADD CONSTRAINT CK_EXCURSION
	CHECK (APIE IN('S', 'N'));
	

CREATE TABLE VISITANTE(
	DNI			CHAR(9),
	NOMBRE		VARCHAR2(50),
	DOMICILIO	VARCHAR2(100),
	PROFESION	VARCHAR2(40)
	);
	
ALTER TABLE VISITANTE ADD CONSTRAINT PK_VISITANTE
	PRIMARY KEY(DNI);
	
CREATE TABLE E_V(
	COD_EXCURSION	NUMBER(4),
	DNI				CHAR(9)
	);
	
ALTER TABLE E_V ADD CONSTRAINT PK_E_V
	PRIMARY KEY(COD_EXCURSION, DNI);
	
ALTER TABLE E_V ADD CONSTRAINT FK1_E_V
	FOREIGN KEY(COD_EXCURSION)
	REFERENCES EXCURSION(COD_EXCURSION);
	
ALTER TABLE E_V ADD CONSTRAINT FK2_E_V
	FOREIGN KEY(DNI)
	REFERENCES VISITANTE(DNI);
	
CREATE TABLE A_V(
	COD_ALOJAMIENTO	NUMBER(2),
	DNI				CHAR(9),	
	FECHA_INICIO	DATE,
	FECHA_FIN		DATE
	);
	
ALTER TABLE A_V ADD CONSTRAINT PK_A_V
	PRIMARY KEY(COD_ALOJAMIENTO, DNI, FECHA_INICIO);
	
ALTER TABLE A_V ADD CONSTRAINT FK1_A_V
	FOREIGN KEY(COD_ALOJAMIENTO)
	REFERENCES ALOJAMIENTO(COD_ALOJAMIENTO);
	
ALTER TABLE A_V ADD CONSTRAINT FK2_A_V
	FOREIGN KEY(DNI)
	REFERENCES VISITANTE(DNI);
	
CREATE TABLE AREA(
	NOMBREA		VARCHAR2(20),
	EXTENSION	NUMBER(4),
	CODPN		NUMBER(4)
	);
	
ALTER TABLE AREA ADD CONSTRAINT PK_AREA
	PRIMARY KEY(NOMBREA);
	
ALTER TABLE AREA ADD CONSTRAINT FK_AREA
	FOREIGN KEY(CODPN)
	REFERENCES PARQUE_NATURAL(CODPN);
	
CREATE TABLE ESPECIE(
	COD_ESPECIE			NUMBER(4),
	NOMBRE_CIENTIFICO	VARCHAR2(100),
	NOMBRE_VULGAR		VARCHAR2(100)
	);
	
ALTER TABLE ESPECIE ADD CONSTRAINT PK_ESPECIE
	PRIMARY KEY(COD_ESPECIE);
	
CREATE TABLE E_A(
	COD_ESPECIE		NUMBER(4),
	COD_AREA		VARCHAR2(20),
	CANT_INDIVIDUOS	NUMBER(6)
	);
	
ALTER TABLE E_A ADD CONSTRAINT PK_E_A
	PRIMARY KEY(COD_ESPECIE, COD_AREA);
	
ALTER TABLE E_A ADD CONSTRAINT FK1_E_A
	FOREIGN KEY(COD_ESPECIE)
	REFERENCES ESPECIE(COD_ESPECIE);
	
ALTER TABLE E_A ADD CONSTRAINT FK2_E_A
	FOREIGN KEY(COD_AREA)
	REFERENCES AREA(NOMBREA);

CREATE TABLE ANIMAL(
	COD_ESPECIE		NUMBER(4),
	ALIMENTACION	VARCHAR2(100),
	PERIODO_CELO	VARCHAR2(20)
	);
	
	
ALTER TABLE ANIMAL ADD CONSTRAINT PK_ANIMAL
	PRIMARY KEY(COD_ESPECIE);
	
ALTER TABLE ANIMAL ADD CONSTRAINT FK_ANIMAL
	FOREIGN KEY(COD_ESPECIE)
	REFERENCES ESPECIE(COD_ESPECIE);
	
CREATE TABLE VEGETAL(
	COD_ESPECIE			NUMBER(4),
	FLORACION			VARCHAR2(20),
	PERIODO_FLORACION	VARCHAR2(20)
	);
	
ALTER TABLE VEGETAL ADD CONSTRAINT PK_VEGETAL
	PRIMARY KEY(COD_ESPECIE);
	
ALTER TABLE VEGETAL ADD CONSTRAINT FK_VEGETAL
	FOREIGN KEY(COD_ESPECIE)
	REFERENCES ESPECIE(COD_ESPECIE);
	
CREATE TABLE MINERAL(
	COD_ESPECIE	NUMBER(4),
	TIPO		VARCHAR2(20)
	);
	
ALTER TABLE MINERAL ADD CONSTRAINT PK_MINERAL
	PRIMARY KEY(COD_ESPECIE);
	
ALTER TABLE MINERAL ADD CONSTRAINT FK_MINERAL
	FOREIGN KEY(COD_ESPECIE)
	REFERENCES ESPECIE(COD_ESPECIE);
	
CREATE TABLE PERSONAL(
	DNI				CHAR(9),	
	NSS				CHAR(12),
	NOMBRE			VARCHAR2(40),
	DIRECCION		VARCHAR2(100),
	TFNO_DOMICILIO	CHAR(9),
	TFNO_MOVIL		CHAR(9),
	SUELDO			NUMBER,
	CODPN			NUMBER(4)
	);
	
ALTER TABLE PERSONAL ADD CONSTRAINT PK_PERSONAL
	PRIMARY KEY(DNI);
	
ALTER TABLE PERSONAL ADD CONSTRAINT UK_PERSONAL
	UNIQUE(NSS);
	
ALTER TABLE PERSONAL ADD CONSTRAINT FK_PERSONAL
	FOREIGN KEY(CODPN)
	REFERENCES PARQUE_NATURAL(CODPN);
	
CREATE TABLE CONSERVADOR(
	DNI		CHAR(9),
	TAREA	VARCHAR2(40),
	NOMBREA	VARCHAR2(20)
	);
	
	
ALTER TABLE CONSERVADOR ADD CONSTRAINT PK_CONSERVADOR
	PRIMARY KEY(DNI);
	
ALTER TABLE CONSERVADOR ADD CONSTRAINT FK1_CONSERVADOR
	FOREIGN KEY(DNI)
	REFERENCES PERSONAL(DNI);
	
ALTER TABLE CONSERVADOR ADD CONSTRAINT FK2_CONSERVADOR
	FOREIGN KEY(NOMBREA)
	REFERENCES AREA(NOMBREA);
	
CREATE TABLE VIGILANTE(
	DNI		CHAR(9),
	NOMBREA	VARCHAR2(40)
	);
	
ALTER TABLE VIGILANTE ADD CONSTRAINT PK_VIGILANTE
	PRIMARY KEY(DNI);
	
ALTER TABLE VIGILANTE ADD CONSTRAINT FK1_VIGILANTE
	FOREIGN KEY(DNI)
	REFERENCES PERSONAL(DNI);
	
ALTER TABLE VIGILANTE ADD CONSTRAINT FK2_VIGILANTE
	FOREIGN KEY(NOMBREA)
	REFERENCES AREA(NOMBREA);
	
CREATE TABLE INVESTIGADOR(
	DNI			CHAR(9),
	TITULACION	VARCHAR2(100)
	);
	
ALTER TABLE INVESTIGADOR ADD CONSTRAINT PK_INVESTIGADOR
	PRIMARY KEY(DNI);
	
ALTER TABLE INVESTIGADOR ADD CONSTRAINT FK_INVESTIGADOR
	FOREIGN KEY(DNI)
	REFERENCES PERSONAL(DNI);
	
CREATE TABLE GESTOR(
	DNI			CHAR(9),
	COD_ENTRADA	NUMBER(2)
	);
	
ALTER TABLE GESTOR ADD CONSTRAINT PK_GESTOR
	PRIMARY KEY(DNI);
	
ALTER TABLE GESTOR ADD CONSTRAINT FK1_GESTOR
	FOREIGN KEY(DNI)
	REFERENCES PERSONAL(DNI);
	
ALTER TABLE GESTOR ADD CONSTRAINT FK2_GESTOR
	FOREIGN KEY(COD_ENTRADA)
	REFERENCES ENTRADA(COD_ENTRADA);
	
CREATE TABLE PROYECTO(
	COD_PROY		NUMBER(4),
	PRESUPUESTO		NUMBER,
	FECHA_INICIO	DATE,
	FECHA_FIN		DATE,
	COD_ESPECIE		NUMBER(4)
	);
	
ALTER TABLE PROYECTO ADD CONSTRAINT PK_PROYECTO
	PRIMARY KEY(COD_PROY);
	
ALTER TABLE PROYECTO ADD CONSTRAINT FK_PROYECTO
	FOREIGN KEY(COD_ESPECIE)
	REFERENCES ESPECIE(COD_ESPECIE);
	
CREATE TABLE I_P(
	COD_PROY	NUMBER(4),
	DNI			CHAR(9)
	);

ALTER TABLE I_P ADD CONSTRAINT PK_I_P
	PRIMARY KEY(COD_PROY, DNI);
	
ALTER TABLE I_P ADD CONSTRAINT FK1_I_P
	FOREIGN KEY(COD_PROY)
	REFERENCES PROYECTO(COD_PROY);
	
ALTER TABLE I_P ADD CONSTRAINT FK2_I_P
	FOREIGN KEY(DNI)
	REFERENCES PERSONAL(DNI);
	
CREATE TABLE VEHICULO(
	MATRICULA	CHAR(9),
	TIPO		VARCHAR2(40),
	DNI			CHAR(9)
	);
	
ALTER TABLE VEHICULO ADD CONSTRAINT PK_VEHICULO
	PRIMARY KEY(MATRICULA);
	
ALTER TABLE VEHICULO ADD CONSTRAINT FK_VEHICULO
	FOREIGN KEY(DNI)
	REFERENCES VIGILANTE(DNI);
	
ALTER TABLE VEHICULO ADD CONSTRAINT UK_VEHICULO
	UNIQUE(DNI);
	

