CREATE TABLE CLIENTE(
	COD_CLIENTE	NUMBER(5),
	NOMBRE		VARCHAR(40),
	CALLE		VARCHAR(40),
	NUMERO		NUMBER(3),
	COMUNA		VARCHAR(40),
	CIUDAD		VARCHAR(40)
	);
	
	
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
	PRIMARY KEY (COD_CLIENTE);
	
CREATE TABLE VENTA(
	ID_VENTA	NUMBER(7),
	MONTO_TOTAL	NUMBER,
	COD_CLIENTE	NUMBER(5)
	);
	
ALTER TABLE VENTA ADD CONSTRAINT PK_VENTA
	PRIMARY KEY (ID_VENTA);
	
ALTER TABLE VENTA ADD CONSTRAINT FK_VENTA FOREIGN KEY (COD_CLIENTE)
	REFERENCES CLIENTE (COD_CLIENTE);

CREATE SEQUENCE NUMVENTA;

CREATE TABLE TELEFONO(
	NUMERO	CHAR(9)
	);
	
ALTER TABLE TELEFONO ADD CONSTRAINT PK_TELEFONO
	PRIMARY KEY (NUMERO);
	
CREATE TABLE CATEGORIA(
	ID_CATEGORIA	NUMBER(3),
	NOMBRE			VARCHAR2(40),
	DESCRIPCION		VARCHAR2(100)
	);
	
ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA
	PRIMARY KEY (ID_CATEGORIA);
	
CREATE TABLE PROVEEDOR(
	COD_PROVEEDOR	NUMBER(5),
	NOMBRE			VARCHAR2(40),
	DIRECCION		VARCHAR2(40),
	TELEFONO		CHAR(9),
	WEB				VARCHAR2(100)
	);
	

ALTER TABLE PROVEEDOR ADD CONSTRAINT PK_PROVEEDOR
	PRIMARY KEY (COD_PROVEEDOR);
	
CREATE INDEX NOMBRE_CLIENTE_IDX ON CLIENTE(NOMBRE);
CREATE INDEX NOMBRE_CATEGORIA_IDX ON CATEGORIA(NOMBRE);
CREATE INDEX NOMBRE_PROVEEDOR_IDX ON PROVEEDOR(NOMBRE);
CREATE INDEX CIUDAD_CLIENTE_IDX ON CLIENTE(CIUDAD);

CREATE TABLE PRODUCTO(
	ID_PRODUCTO		NUMBER(5),
	NOMBRE			VARCHAR2(40),
	PRECIO			NUMBER,	
	STOCK			NUMBER(6),
	ID_CATEGORIA	NUMBER(3),
	ID_PROVEEDOR	NUMBER(5)
	);
	

ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTO
	PRIMARY KEY(ID_PRODUCTO);
	
ALTER TABLE PRODUCTO ADD CONSTRAINT FK1_PROD_CATEGORIA FOREIGN KEY (ID_CATEGORIA)
	REFERENCES CATEGORIA(ID_CATEGORIA);
	
ALTER TABLE PRODUCTO ADD CONSTRAINT FK2_PROD_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR)
	REFERENCES PROVEEDOR(COD_PROVEEDOR);
	
CREATE TABLE ASOCIADO(
	COD_CLIENTE		NUMBER(5),
	NUM_TELEFONO	CHAR(9)
	);
	
ALTER TABLE ASOCIADO ADD CONSTRAINT PK_ASOCIADO
	PRIMARY KEY (COD_CLIENTE, NUM_TELEFONO);
	
ALTER TABLE ASOCIADO ADD CONSTRAINT FK1_CLIENTE FOREIGN KEY(COD_CLIENTE)
	REFERENCES CLIENTE(COD_CLIENTE);
	
ALTER TABLE ASOCIADO ADD CONSTRAINT FK2_TELEFONO FOREIGN KEY(NUM_TELEFONO)
	REFERENCES TELEFONO(NUMERO);
	
CREATE TABLE INCLUYE(
	ID_VENTA		NUMBER(7),
	ID_PRODUCTO		NUMBER(5),
	CANTIDAD		NUMBER(5),
	PRECIO_VENTA	NUMBER
	);
	
ALTER TABLE INCLUYE ADD CONSTRAINT PK_INCLUYE,
	PRIMARY KEY(ID_VENTA, ID_PRODUCTO);

ALTER TABLE INCLUYE ADD CONSTRAINT FK1_INCLUYE FOREIGN KEY(ID_VENTA)
	REFERENCES VENTA(ID_VENTA);
	
ALTER TABLE INCLUYE ADD CONSTRAINT FK2_INCLUYE FOREIGN KEY(ID_PRODUCTO)
	REFERENCES PRODUCTO(ID_PRODUCTO);
	

