CREATE TABLE DIRECTOR(
	NOMBRE			VARCHAR2(40) CONSTRAINT PK_DIRECTOR PRIMARY KEY,
	NACIONALIDAD	VARCHAR(40)
	);
	
CREATE TABLE PELICULA(
	ID				NUMBER(4) CONSTRAINT PK_PELICULA PRIMARY KEY,
	TITULO			VARCHAR2(40) CONSTRAINT NN_TITULO NOT NULL,
	PRODUCTORA		VARCHAR2(40),
	NACIONALIDAD	VARCHAR2(40),	
	FECHA			DATE,
	DIRECTOR		VARCHAR2(40) CONSTRAINT FK_DIRECTOR
		REFERENCES DIRECTOR (NOMBRE)
	);
	
CREATE TABLE EJEMPLAR(
	ID_PELI	NUMBER(4),
	NUMERO	NUMBER(2),
	ESTADO	VARCHAR2(40),
	CONSTRAINT PK_EJEMPLAR PRIMARY KEY (ID_PELI, NUMERO);
	CONSTRAINT FK_PELICULA_EJEMPLAR FOREIGN KEY (ID_PELI)
		REFERENCES PELICULA(ID)
	);
	
CREATE TABLE ACTORES(
	NOMBRE			VARCHAR2(40) CONSTRAINT PK_ACTORES PRIMARY KEY,
	NACIONALIDAD	VARCHAR2(40),	
	SEXO			CHAR(1),
	CONSTRAINT CK_SEXO CHECK (SEXO IN ('H', 'M'))
	);

CREATE TABLE SOCIO(
	DNI			CHAR(9) CONSTRAINT PK_SOCIO PRIMARY KEY,
	NOMBRE		VARCHAR2(40) CONSTRAINT NN_NOMBRE NOT NULL,
	DIRECCION	VARCHAR2(40),
	TELEFONO	CHAR(9),
	AVALADOR	CHAR(9)
	CONSTRAINT FK_SOCIO FOREIGN KEY (AVALADOR)
		REFERENCES SOCIO (DNI)
	);
	
CREATE TABLE ACTUA(
	ACTOR		VARCHAR2(40),
	ID_PELI		NUMBER(4),
	PROTA		CHAR(2) DEFAULT ('NO'),
	CONSTRAINT PK_ACTUA PRIMARY KEY (ACTOR, ID_PELI),
	CONSTRAINT FK1_ACTORES_ACTUA FOREIGN KEY (ACTOR_NOMBRE)
		REFERENCES ACTORES (NOMBRE),
	CONSTRAINT FK_PELICULA_ID FOREIGN KEY (ID_PELI)
		REFERENCES PELICULA (ID),
	CONSTRAINT CK_PROTA CHECK (PROTAGONISTA IN ('SI', 'NO'))
	);
	
CREATE TABLE ALQUILA(
	DNI					CHAR(9),
	ID_PELI				NUMBER(4),
	NUMERO				NUMBER(2),
	FECHAALQUILER		DATE,
	FECHADEVOLUCION		DATE,
	CONSTRAINT PK_ALQUILA PRIMARY KEY (DNI, ID_PELI, NUMERO, FECHAALQUILER),
	CONSTRAINT FK1_DNI FOREIGN KEY (DNI)
		REFERENCES SOCIO (DNI),
	CONSTRAINT FK2_PELI FOREIGN KEY (ID_PELI, NUMERO)
		REFERENCES EJEMPLAR(ID_PELI, NUMERO),
	CONSTRAINT CK_FECHA CHECK (FECHADEVOLUCION > FECHAALQUILER)
	);
	