CREATE TABLE CLIENTE(
	DNI			CHAR(9),
	NOMBRE		VARCHAR2(40),
	DIRECCION	VARCHAR2(40),
	LOCALIDAD	VARCHAR2(40),
	FECHA_NAC	DATE,
	SEXO		CHAR(1)
	);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
	PRIMARY KEY(DNI);
	
ALTER TABLE CLIENTE ADD CONSTRAINT
	CHECK (SEXO IN ('H', 'M'));
	

CREATE TABLE SUCURSAL(
	COD_SUCURSAL	NUMBER(4),
	NOMBRE			VARCHAR2(40),
	DIRECCION		VARCHAR2(40),
	LOCALIDAD		VARCHAR2(40)
	);

ALTER TABLE SUCURSAL ADD CONSTRAINT PK_SUCURSAL
	PRIMARY KEY (COD_SUCURSAL);
	
CREATE SEQUENCE NUMSUCURSAL;

CREATE INDEX NOMBRE_CLIENTE_IDX ON CLIENTE (NOMBRE);
CREATE INDEX NOMBRE_SUCURSAL_IDX ON SUCURSAL (NOMBRE);
CREATE INDEX LOCALIDAD_CLIENTE_IDX ON CLIENTE (LOCALIDAD);
CREATE INDEX LOCALIDAD_SUCURSAL_IDX ON SUCURSAL (LOCALIDAD);

CREATE TABLE CUENTA(
	COD_SUCURSAL NUMBER(4),
	COD_CUENTA	 CHAR(20)
	);
	
ALTER TABLE CUENTA ADD CONSTRAINT PK_CUENTA
	PRIMARY KEY (COD_SUCURSAL, COD_CUENTA);
	
ALTER TABLE CUENTA ADD CONSTRAINT FK_CUENTA (COD_SUCURSAL)
	REFERENCES SUCURSAL (COD_SUCURSAL);
	
CREATE TABLE TRANSACCION(
	COD_SUCURSAL	NUMBER(4),
	COD_CUENTA		CHAR(20),
	NUM_TRANSACCION	NUMBER(5),
	FECHA			DATE,
	CANTIDAD		NUMBER(8),
	TIPO			VARCHAR2(20)
	);
	
ALTER TABLE TRANSACCION ADD CONSTRAINT PK_TRANSACCION
	PRIMARY KEY (COD_SUCURSAL, COD_CUENTA, NUM_TRANSACCION);
	
ALTER TABLE TRANSACCION ADD CONSTRAINT FK_TRANSACCION FOREIGN KEY (COD_SUCURSAL, COD_CUENTA)
	REFERENCES CUENTA (COD_SUCURSAL, COD_CUENTA);
	
CREATE TABLE CLI_CUENTA(
	COD_SUCURSAL	NUMBER(4),
	COD_CUENTA		CHAR(20),
	DNI				CHAR(9)
	);

ALTER TABLE CLI_CUENTA ADD CONSTRAINT PK_CLI_CUENTA
	PRIMARY KEY (COD_SUCURSAL, COD_CUENTA, DNI);
	
ALTER TABLE CLI_CUENTA ADD CONSTRAINT FK1_CLI_CUENTA FOREIGN KEY (COD_SUCURSAL, COD_CUENTA)
	REFERENCES CUENTA (COD_SUCURSAL, COD_CUENTA);
	
ALTER TABLE CLI_CUENTA ADD CONSTRAINT FK2_CLI_CUENTA FOREIGN KEY (DNI)
	REFERENCES CLIENTE(DNI);
	







