CREATE TABLE CCC(
	ID_CUENTA		NUMBER(7),
	COD_BANCO		NUMBER(4),
	COD_SUCURSAL	NUMBER(4),
	NUM_CUENTA		NUMBER(10)
	);
	
ALTER TABLE CCC ADD CONSTRAINT PK_CCC
	PRIMARY KEY(ID_CUENTA);
	
ALTER TABLE CCC ADD CONSTRAINT UK_CCC
	UNIQUE(COD_BANCO, COD_SUCURSAL, NUM_CUENTA);
	
CREATE SEQUENCE ID_CUENTA;

CREATE TABLE EMPLEADO(
	COD_EMPLEADO	NUMBER(5),
	NIF				CHAR(9),
	NOMBRE			VARCHAR2(40),
	NUM_HIJOS		NUMBER(2),
	RETENCION		NUMBER(4,2),
	ID_CUENTA		NUMBER(7)
	);
	
ALTER TABLE EMPLEADO ADD CONSTRAINT PK_EMPLEADO
	PRIMARY KEY(COD_EMPLEADO);
	
ALTER TABLE EMPLEADO ADD CONSTRAINT UK_EMPLEADO
	UNIQUE(NIF);
	
ALTER TABLE EMPLEADO ADD CONSTRAINT FK_EMPLEADO
	FOREIGN KEY(ID_CUENTA)
	REFERENCES CCC(ID_CUENTA);
	
CREATE TABLE NOMINA(
	ID_NOMINA		NUMBER(7),
	ID_CUENTA		NUMBER(7),
	EJERC_FISCAL	NUMBER(4),
	MES				VARCHAR2(15),
	NUM_ORDEN		NUMBER(1),
	COD_EMP			NUMBER(5)
	);
	
CREATE SEQUENCE ID_NOMINA;

ALTER TABLE NOMINA ADD CONSTRAINT PK_NOMINA
	PRIMARY KEY(ID_NOMINA);
	
ALTER TABLE NOMINA ADD CONSTRAINT UK_NOMINA
	UNIQUE(ID_CUENTA, EJERC_FISCAL, MES, NUM_ORDEN);
	
ALTER TABLE NOMINA ADD CONSTRAINT FK1_NOMINA
	FOREIGN KEY(ID_CUENTA)
	REFERENCES CCC(ID_CUENTA);
	
ALTER TABLE NOMINA ADD CONSTRAINT FK2_NOMINA
	FOREIGN KEY(COD_EMP)
	REFERENCES EMPLEADO(COD_EMP);
	
CREATE TABLE DEPARTAMENTO(
	COD_DPTO	NUMBER(3),
	NOMBRE		VARCHAR2(40)
	);
	
ALTER TABLE DEPARTAMENTO ADD CONSTANT PK_DEPARTAMENTO
	PRIMARY KEY(COD_DPTO);
	
CREATE TABLE SEDE(
	COD_SEDE	NUMBER(2),
	NOMBRE		VARCHAR2(40),
	COD_DPTO	NUMBER(3)
	);
	
ALTER TABLE SEDE ADD CONSTRAINT PK_SEDE
	PRIMARY KEY(COD_SEDE);
	
ALTER TABLE SEDE ADD CONSTRAINT FK_SEDE
	FOREIGN KEY(COD_DPTO)
	REFERENCES DEPARTAMENTO(COD_DPTO);
	
CREATE TABLE TRABAJA(
	COD_EMP		NUMBER(5),
	COD_DPTO	NUMBER(3),
	FUNCION		VARCHAR2(50)
	);
	
ALTER TABLE TRABAJA ADD CONSTRAINT PK_TRABAJA
	PRIMARY KEY(COD_EMP, COD_DPTO);
	
ALTER TABLE TRABAJA ADD CONSTRAINT FK1_TRABAJA
	FOREIGN KEY(COD_EMP)
	REFERENCES EMPLEADO(COD_EMP);
	
ALTER TABLE TRABAJA ADD CONSTRAINT FK2_TRABAJA
	FOREIGN KEY(COD_DPTO)
	REFERENCES DEPARTAMENTO(COD_DPTO);
	
CREATE TABLE CONCEPTO_RETRIBUTIVO(
	COD				NUMBER(2),
	DESCRIPCION		VARCHAR2(100)
	);
	
ALTER TABLE CONCEPTO_RETRIBUTIVO ADD CONSTRAINT PK_CONCEPTO_RETRIBUTIVO
	PRIMARY KEY(COD);
	
CREATE TABLE INGRESO(
	ID_NOMINA	NUMBER(7),
	LINEA_NUM	NUMBER(3),
	CANTIDAD	NUMBER,
	CONCEPTO	NUMBER(2)
	);
	
CREATE SEQUENCE LINEA_NUM;

ALTER TABLE INGRESO ADD CONSTRAINT PK_INGRESO
	PRIMARY KEY(ID_NOMINA, LINEA_NUM);
	
ALTER TABLE INGRESO ADD CONSTRAINT FK1_INGRESO
	FOREIGN KEY(ID_NOMINA)
	REFERENCES NOMINA(ID_NOMINA);
	
ALTER TABLE INGRESO ADD CONSTRAINT FK2_INGRESO
	FOREIGN KEY(CONCEPTO)
	REFERENCES CONCEPTO_RETRIBUTIVO(COD);
	
CREATE TABLE DESCUENTO(
	ID_NOMINA	NUMBER(7),
	LINEA_NUM	NUMBER(3),
	CANTIDAD	NUMBER,
	BASE		NUMBER,
	PORCENTAJE	NUMBER(4,2)
	);
	
ALTER TABLE DESCUENTO ADD CONSTRAINT PK_DESCUENTO
	PRIMARY KEY(ID_NOMINA, LINEA_NUM);
	
ALTER TABLE DESCUENTO ADD CONSTRAINT FK_DESCUENTO
	FOREIGN KEY(ID_NOMINA)
	REFERENCES NOMINA(ID_NOMINA);
	
