--EJERCICIO1

--En primer lugar vamos a crear la tabla Familia, y sus restricciones

CREATE TABLE FAMILIA(
    CODFAMILIA  NUMBER(3),
    DENOFAMILIA VARCHAR2(50)NOT NULL
    );
    
ALTER TABLE FAMILIA ADD CONSTRAINT PK_FAMILIA
PRIMARY KEY(CODFAMILIA);

ALTER TABLE FAMILIA ADD CONSTRAINT UK_DENOFAMILIA
UNIQUE(DENOFAMILIA);

--A continuación, haremos lo mismo para la tabla Producto, y sus restricciones.

CREATE TABLE PRODUCTO(
    CODPRODUCTO     NUMBER(5),
    DENOPRODUCTO    VARCHAR2(20) NOT NULL,
    DESCRIPCION     VARCHAR2(100),
    PRECIOBASE      NUMBER(8,2) NOT NULL,
    PORCREPOSICION  NUMBER(3),
    UNIDADESMINIMAS NUMBER(4) NOT NULL,
    CODFAMILIA      NUMBER(3) NOT NULL
    );
    
ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTO
PRIMARY KEY(CODPRODUCTO);

ALTER TABLE PRODUCTO ADD CONSTRAINT CK_PRECIOBASE
CHECK (PRECIOBASE > 0);

ALTER TABLE PRODUCTO ADD CONSTRAINT CK_PORCREPOSICION
CHECK (PORCREPOSICION >0);

ALTER TABLE PRODUCTO ADD CONSTRAINT CK_UNIDADESMINIMAS
CHECK (UNIDADESMINIMAS > 0);

ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTO
FOREIGN KEY(CODFAMILIA)
REFERENCES FAMILIA(CODFAMILIA) ON DELETE CASCADE;

--Continuamos con la tabla Tienda y sus restricciones.

CREATE TABLE TIENDA(
    CODTIENDA       NUMBER(3),
    DENOTIENDA      VARCHAR2(20) NOT NULL,
    TELEFONO        CHAR(11),
    CODIGOPOSTAL    CHAR(5) NOT NULL,
    PROVINCIA       VARCHAR2(5) NOT NULL
    );
    
ALTER TABLE TIENDA ADD CONSTRAINT PK_TIENDA
PRIMARY KEY(CODTIENDA);

--Es el turno de la tabla Stock y sus restricciones.

CREATE TABLE STOCK(
    CODTIENDA   NUMBER(3) NOT NULL,
    CODPRODUCTO NUMBER(5) NOT NULL,
    UNIDADES    NUMBER(6) NOT NULL
    );

ALTER TABLE STOCK ADD CONSTRAINT PK_STOCK
PRIMARY KEY(CODTIENDA, CODPRODUCTO);

ALTER TABLE STOCK ADD CONSTRAINT FK1_STOCK_CODTIENDA
FOREIGN KEY(CODTIENDA)
REFERENCES TIENDA(CODTIENDA) ON DELETE CASCADE;

ALTER TABLE STOCK ADD CONSTRAINT FK2_STOCK_CODPRODUCTO
FOREIGN KEY(CODPRODUCTO)
REFERENCES PRODUCTO(CODPRODUCTO) ON DELETE CASCADE;

ALTER TABLE STOCK ADD CONSTRAINT CK_STOCK_UNIDADES
CHECK (UNIDADES>=0);








